def removeJavaKeyword():
    f3 = open('output1.txt', 'r+', encoding="utf8")
    f4 = open('output2.txt', 'w+', encoding="utf8")

    delete_list = [ "_",
                    "-",
                    "$",
                    "bridge",
                    "From",
                    "Click",
                    "View",
                    "Layout",
                    "Drawable",
                    "View",
                    "Button",
                    "Menu",
                    "Title",
                    "Icon",
                    "All",
                    "Item",
                    "Down",
                    "Drop",
                    "<init>",
                    "<clinit>",
                    "synthetic",
                    "run",
                    "declared",
                    "-,"
                    "create",
                    "execute",
                    "get",
                    "Value",
                    "value",
                    " to",
                    " To",
                    "String",
                    "has",
                    "Next",
                    "next",
                    "iterator",
                    " on",
                    "set",
                    "false",
                    "true",
                    "abstract",
                    "assert",
                    "boolean",
                    "break",
                    "byte",
                    "case",
                    "catch",
                    "char",
                    "class",
                    "constructor",
                    "const",
                    "continue",
                    "default",
                    "do",
                    "double",
                    "else",
                    "enum",
                    "extends",
                    "final",
                    "finally",
                    "float",
                    "for",
                    "goto",
                    "if",
                    "implements",
                    "import",
                    "instanceof",
                    "int",
                    "interface",
                    "long",
                    "native",
                    "new",
                    "null",
                    "package",
                    "private",
                    "protected",
                    "public",
                    "return",
                    "short",
                    "static",
                    "super",
                    "switch",
                    "synchronized",
                    "this",
                    "throw",
                    "throws",
                    "transient",
                    "null",
                    "try",
                    "void",
                    "volatile",
                    "while",
                   ]

    try:
        for line in f3:
          for word in delete_list:
              line = line.replace(word,"") # Replace all the java keyword with nothing
          f4.write(line)

    except IndexError:
        i = 0

    f3.close()
    f4.close()

    return